name: Generate PDF

on:
  push:
    branches: [ documentation_auto ]

permissions:
  contents: write

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build PDF
        uses: BaileyJM02/markdown-to-pdf@v1
        with:
          input_dir: docs   # It looks for MD files here
          output_dir: pdfs  # It saves the PDF here
          images_dir: docs/images # Explicitly tell it where images are (optional but safe)
          
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Documentation
          path: pdfs/*.pdf