name: Generate PDF

on:
  push:
    branches: [ documentation_auto ]

permissions:
  contents: write

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest
    steps:
      # 1. Récupère le code (Version v4 à jour)
      - uses: actions/checkout@v4

      # 2. Convertit le Markdown en PDF
      - name: Build PDF
        uses: BaileyJM02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          # Ici, on dit au script que les images sont au même endroit que le md
          images_dir: docs
          
      # 3. Sauvegarde le PDF pour que tu puisses le télécharger
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Documentation-Projet
          path: pdfs/*.pdf
          overwrite: true