name: Generate PDF with Pandoc

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Cette action utilise Pandoc et gère mieux les images
      - name: Build PDF using Pandoc
        uses: docker://pandoc/core:2.9
        with:
          args: >-
            -f markdown
            -t html5
            --output=doc.pdf
            docs/doc.md
            --resource-path=docs
            --standalone
            --css=.github/style.css
            
      # Note : Pandoc génère le PDF à la racine ici (ou là où on lui dit)
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Documentation-Projet
          path: doc.pdf